export default {
  Hide: require('../assets/images/Hide.png'),
  IconGoogle: require('../assets/images/IconGoogle.png'),
  IconApple: require('../assets/images/IconApple.png'),
  Logo: require('../assets/images/Logo.png'),
  Notifications: require('../assets/images/Notifications.png'),
  Edit: require('../assets/images/Edit.png'),
  IconMyChannel: require('../assets/images/IconMyChannel.png'),
  IconSubscriptions: require('../assets/images/IconSubscriptions.png'),
  IconPaymentMethods: require('../assets/images/IconPaymentMethods.png'),
  IconProfile: require('../assets/images/IconProfile.png'),
  IconNotfications: require('../assets/images/IconNotfications.png'),
  IconPreferences: require('../assets/images/IconPreferences.png'),
  IconSecurity: require('../assets/images/IconSecurity.png'),
  IconLanguages: require('../assets/images/IconLanguages.png'),
  IconDarkMode: require('../assets/images/IconDarkMode.png'),
  IconHelp: require('../assets/images/IconHelp.png'),
  IconInvite: require('../assets/images/IconInvite.png'),
  IconCommunity: require('../assets/images/IconCommunity.png'),
  IconTerms: require('../assets/images/IconTerms.png'),
  IconAbout: require('../assets/images/IconAbout.png'),
  IconLogout: require('../assets/images/IconLogout.png'),
  sf: require('../assets/images/SF.png'),
  Image: require('../assets/images/Image.png'),
  Camera: require('../assets/images/Camera.png'),
  Done: require('../assets/images/Done.png'),
  Avatar: require('../assets/images/Avatar.png'),
};
